[2025-04-16T06:46:22.838+0000] {processor.py:153} INFO - Started process (PID=452) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:46:22.839+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:46:22.840+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:46:22.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:46:22.958+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:46:22.957+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:46:22.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:46:22.991+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.158 seconds
[2025-04-16T06:46:53.048+0000] {processor.py:153} INFO - Started process (PID=457) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:46:53.057+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:46:53.058+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:46:53.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:46:53.172+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:46:53.170+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:46:53.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:46:53.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.165 seconds
[2025-04-16T06:47:23.377+0000] {processor.py:153} INFO - Started process (PID=462) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:47:23.387+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:47:23.388+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:47:23.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:47:23.491+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:47:23.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:47:23.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:47:23.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.146 seconds
[2025-04-16T06:47:53.588+0000] {processor.py:153} INFO - Started process (PID=467) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:47:53.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:47:53.591+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:47:53.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:47:53.709+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:47:53.708+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:47:53.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:47:53.745+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.162 seconds
[2025-04-16T06:48:23.908+0000] {processor.py:153} INFO - Started process (PID=472) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:48:23.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:48:23.911+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:48:23.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:48:24.023+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:48:24.021+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:48:24.023+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:48:24.068+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.165 seconds
[2025-04-16T06:48:54.121+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:48:54.122+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:48:54.124+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:48:54.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:48:54.246+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:48:54.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:48:54.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:48:54.292+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.176 seconds
[2025-04-16T06:49:24.458+0000] {processor.py:153} INFO - Started process (PID=482) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:49:24.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:49:24.460+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:49:24.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:49:24.566+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:49:24.565+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:49:24.567+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:49:24.602+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.149 seconds
[2025-04-16T06:49:54.664+0000] {processor.py:153} INFO - Started process (PID=487) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:49:54.673+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:49:54.675+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:49:54.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:49:54.813+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:49:54.811+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:49:54.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:49:54.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.198 seconds
[2025-04-16T06:50:24.985+0000] {processor.py:153} INFO - Started process (PID=492) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:50:24.994+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:50:24.995+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:50:24.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:50:25.114+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:50:25.113+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:50:25.115+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:50:25.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.171 seconds
[2025-04-16T06:50:55.238+0000] {processor.py:153} INFO - Started process (PID=497) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:50:55.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:50:55.248+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:50:55.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:50:55.357+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:50:55.355+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:50:55.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:50:55.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.160 seconds
[2025-04-16T06:51:25.510+0000] {processor.py:153} INFO - Started process (PID=502) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:51:25.519+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:51:25.520+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:51:25.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:51:25.621+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:51:25.620+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:51:25.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:51:25.651+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.146 seconds
[2025-04-16T06:51:55.747+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:51:55.748+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:51:55.749+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:51:55.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:51:55.853+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:51:55.852+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:51:55.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:51:55.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.150 seconds
[2025-04-16T06:52:26.035+0000] {processor.py:153} INFO - Started process (PID=512) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:52:26.044+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:52:26.046+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:52:26.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:52:26.148+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:52:26.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:52:26.149+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:52:26.187+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.156 seconds
[2025-04-16T06:52:56.261+0000] {processor.py:153} INFO - Started process (PID=517) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:52:56.270+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:52:56.271+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:52:56.271+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:52:56.385+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:52:56.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:52:56.386+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:52:56.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.160 seconds
[2025-04-16T06:53:26.573+0000] {processor.py:153} INFO - Started process (PID=522) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:53:26.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:53:26.584+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:53:26.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:53:26.682+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:53:26.681+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:53:26.683+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:53:26.720+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.152 seconds
[2025-04-16T06:53:56.799+0000] {processor.py:153} INFO - Started process (PID=527) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:53:56.808+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:53:56.809+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:53:56.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:53:56.911+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:53:56.910+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:53:56.912+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:53:56.942+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.148 seconds
[2025-04-16T06:54:27.099+0000] {processor.py:153} INFO - Started process (PID=532) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:54:27.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:54:27.109+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:54:27.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:54:27.223+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:54:27.221+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:54:27.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:54:27.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.171 seconds
[2025-04-16T06:54:57.308+0000] {processor.py:153} INFO - Started process (PID=537) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:54:57.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:54:57.319+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:54:57.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:54:57.422+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:54:57.421+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:54:57.423+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:54:57.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.147 seconds
[2025-04-16T06:55:27.644+0000] {processor.py:153} INFO - Started process (PID=542) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:55:27.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:55:27.654+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:55:27.654+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:55:27.752+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:55:27.751+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:55:27.752+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:55:27.789+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.149 seconds
[2025-04-16T06:55:57.845+0000] {processor.py:153} INFO - Started process (PID=547) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:55:57.855+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:55:57.856+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:55:57.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:55:57.964+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:55:57.962+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:55:57.964+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:55:58.004+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.164 seconds
[2025-04-16T06:56:28.203+0000] {processor.py:153} INFO - Started process (PID=552) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:56:28.212+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:56:28.214+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:56:28.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:56:28.332+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:56:28.330+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:56:28.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:56:28.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.175 seconds
[2025-04-16T06:56:58.581+0000] {processor.py:153} INFO - Started process (PID=557) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:56:58.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:56:58.592+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:56:58.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:56:58.696+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:56:58.694+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:56:58.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:56:58.734+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.157 seconds
[2025-04-16T06:57:28.935+0000] {processor.py:153} INFO - Started process (PID=562) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:57:28.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:57:28.946+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:57:28.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:57:29.060+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:57:29.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:57:29.060+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:57:29.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.166 seconds
[2025-04-16T06:57:59.297+0000] {processor.py:153} INFO - Started process (PID=567) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:57:59.298+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:57:59.300+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:57:59.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:57:59.399+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:57:59.397+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:57:59.399+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:57:59.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.142 seconds
[2025-04-16T06:58:29.490+0000] {processor.py:153} INFO - Started process (PID=572) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:58:29.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:58:29.501+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:58:29.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:58:29.598+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:58:29.597+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:58:29.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:58:29.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.152 seconds
[2025-04-16T06:58:59.831+0000] {processor.py:153} INFO - Started process (PID=577) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:58:59.841+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:58:59.842+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:58:59.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:58:59.958+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:58:59.957+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:58:59.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:58:59.995+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.168 seconds
[2025-04-16T06:59:30.195+0000] {processor.py:153} INFO - Started process (PID=582) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T06:59:30.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T06:59:30.206+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:59:30.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T06:59:30.310+0000] {logging_mixin.py:137} INFO - [2025-04-16T06:59:30.309+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T06:59:30.311+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T06:59:30.349+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.159 seconds
[2025-04-16T07:00:00.554+0000] {processor.py:153} INFO - Started process (PID=587) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:00:00.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:00:00.557+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:00:00.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:00:00.654+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:00:00.653+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:00:00.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:00:00.692+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.142 seconds
[2025-04-16T07:00:30.744+0000] {processor.py:153} INFO - Started process (PID=592) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:00:30.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:00:30.754+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:00:30.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:00:30.866+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:00:30.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:00:30.866+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:00:30.912+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.173 seconds
[2025-04-16T07:01:01.090+0000] {processor.py:153} INFO - Started process (PID=597) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:01:01.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:01:01.092+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:01:01.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:01:01.193+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:01:01.192+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:01:01.194+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:01:01.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.140 seconds
[2025-04-16T07:01:31.314+0000] {processor.py:153} INFO - Started process (PID=602) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:01:31.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:01:31.325+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:01:31.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:01:31.447+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:01:31.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:01:31.447+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:01:31.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.179 seconds
[2025-04-16T07:02:01.622+0000] {processor.py:153} INFO - Started process (PID=607) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:02:01.632+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:02:01.634+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:02:01.634+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:02:01.765+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:02:01.763+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:02:01.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:02:01.802+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.185 seconds
[2025-04-16T07:02:31.975+0000] {processor.py:153} INFO - Started process (PID=612) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:02:31.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:02:31.984+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:02:31.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:02:32.048+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:02:32.047+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:02:32.048+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:02:32.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.093 seconds
[2025-04-16T07:03:02.152+0000] {processor.py:153} INFO - Started process (PID=617) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:03:02.154+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:03:02.155+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:03:02.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:03:02.261+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:03:02.260+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:03:02.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:03:02.297+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.150 seconds
[2025-04-16T07:03:32.430+0000] {processor.py:153} INFO - Started process (PID=622) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:03:32.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:03:32.440+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:03:32.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:03:32.556+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:03:32.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:03:32.557+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:03:32.589+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.165 seconds
[2025-04-16T07:04:02.670+0000] {processor.py:153} INFO - Started process (PID=627) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:04:02.679+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:04:02.681+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:04:02.680+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:04:02.782+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:04:02.781+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:04:02.783+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:04:02.818+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.152 seconds
[2025-04-16T07:04:32.957+0000] {processor.py:153} INFO - Started process (PID=632) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:04:32.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:04:32.968+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:04:32.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:04:33.071+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:04:33.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:04:33.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:04:33.107+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.155 seconds
[2025-04-16T07:05:03.187+0000] {processor.py:153} INFO - Started process (PID=637) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:05:03.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:05:03.198+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:05:03.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:05:03.314+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:05:03.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:05:03.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:05:03.352+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.170 seconds
[2025-04-16T07:05:33.482+0000] {processor.py:153} INFO - Started process (PID=642) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:05:33.491+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:05:33.492+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:05:33.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:05:33.609+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:05:33.608+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:05:33.610+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:05:33.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.170 seconds
[2025-04-16T07:06:03.727+0000] {processor.py:153} INFO - Started process (PID=647) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:06:03.736+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:06:03.737+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:06:03.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:06:03.840+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:06:03.839+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:06:03.841+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:06:03.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.155 seconds
[2025-04-16T07:06:34.017+0000] {processor.py:153} INFO - Started process (PID=652) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:06:34.019+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:06:34.020+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:06:34.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:06:34.133+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:06:34.131+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:06:34.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:06:34.169+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.157 seconds
[2025-04-16T07:07:04.240+0000] {processor.py:153} INFO - Started process (PID=657) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:07:04.249+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:07:04.251+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:07:04.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:07:04.366+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:07:04.364+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:07:04.367+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:07:04.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.162 seconds
[2025-04-16T07:07:34.553+0000] {processor.py:153} INFO - Started process (PID=662) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:07:34.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:07:34.564+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:07:34.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:07:34.668+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:07:34.666+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:07:34.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:07:34.696+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.149 seconds
[2025-04-16T07:08:04.793+0000] {processor.py:153} INFO - Started process (PID=667) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:08:04.794+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:08:04.796+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:08:04.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:08:04.925+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:08:04.924+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:08:04.926+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:08:04.967+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.181 seconds
[2025-04-16T07:08:35.079+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:08:35.088+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:08:35.089+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:08:35.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:08:35.189+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:08:35.188+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:08:35.190+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:08:35.227+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.154 seconds
[2025-04-16T07:09:05.345+0000] {processor.py:153} INFO - Started process (PID=677) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:09:05.355+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:09:05.356+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:09:05.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:09:05.466+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:09:05.465+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:09:05.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:09:05.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.163 seconds
[2025-04-16T07:09:35.614+0000] {processor.py:153} INFO - Started process (PID=682) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:09:35.623+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:09:35.625+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:09:35.624+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:09:35.746+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:09:35.745+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:09:35.746+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:09:35.776+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.168 seconds
[2025-04-16T07:10:05.892+0000] {processor.py:153} INFO - Started process (PID=687) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:10:05.893+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:10:05.894+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:10:05.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:10:06.032+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:10:06.030+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:10:06.033+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:10:06.073+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.188 seconds
[2025-04-16T07:10:36.130+0000] {processor.py:153} INFO - Started process (PID=692) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:10:36.139+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:10:36.140+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:10:36.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:10:36.251+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:10:36.250+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:10:36.252+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:10:36.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.165 seconds
[2025-04-16T07:11:06.441+0000] {processor.py:153} INFO - Started process (PID=697) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:11:06.450+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:11:06.452+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:11:06.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:11:06.551+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:11:06.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:11:06.551+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:11:06.588+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.152 seconds
[2025-04-16T07:11:36.673+0000] {processor.py:153} INFO - Started process (PID=702) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:11:36.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:11:36.683+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:11:36.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:11:36.781+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:11:36.780+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:11:36.782+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:11:36.822+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.154 seconds
[2025-04-16T07:12:06.953+0000] {processor.py:153} INFO - Started process (PID=707) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:12:06.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:12:06.963+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:12:06.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:12:07.064+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:12:07.063+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:12:07.064+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:12:07.098+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.149 seconds
[2025-04-16T07:12:37.178+0000] {processor.py:153} INFO - Started process (PID=712) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:12:37.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:12:37.189+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:12:37.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:12:37.298+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:12:37.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:12:37.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:12:37.335+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.162 seconds
[2025-04-16T07:13:07.468+0000] {processor.py:153} INFO - Started process (PID=717) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:13:07.477+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:13:07.478+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:13:07.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:13:07.598+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:13:07.596+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:13:07.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:13:07.644+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.181 seconds
[2025-04-16T07:13:37.707+0000] {processor.py:153} INFO - Started process (PID=722) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:13:37.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:13:37.717+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:13:37.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:13:37.818+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:13:37.817+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:13:37.819+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:13:37.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.153 seconds
[2025-04-16T07:14:08.024+0000] {processor.py:153} INFO - Started process (PID=727) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:14:08.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:14:08.034+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:14:08.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:14:08.149+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:14:08.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:14:08.149+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:14:08.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.169 seconds
[2025-04-16T07:14:38.384+0000] {processor.py:153} INFO - Started process (PID=732) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:14:38.393+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:14:38.395+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:14:38.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:14:38.496+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:14:38.495+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:14:38.496+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:14:38.533+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.154 seconds
[2025-04-16T07:15:08.576+0000] {processor.py:153} INFO - Started process (PID=737) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:15:08.586+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:15:08.587+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:15:08.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:15:08.699+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:15:08.697+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:15:08.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:15:08.740+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.170 seconds
[2025-04-16T07:15:38.904+0000] {processor.py:153} INFO - Started process (PID=742) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:15:38.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:15:38.914+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:15:38.914+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:15:39.028+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:15:39.027+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:15:39.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:15:39.065+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.165 seconds
[2025-04-16T07:16:09.263+0000] {processor.py:153} INFO - Started process (PID=747) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:16:09.272+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:16:09.273+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:16:09.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:16:09.392+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:16:09.391+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:16:09.393+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:16:09.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.174 seconds
[2025-04-16T07:16:39.626+0000] {processor.py:153} INFO - Started process (PID=752) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:16:39.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:16:39.629+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:16:39.629+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:16:39.733+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:16:39.731+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:16:39.733+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:16:39.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.157 seconds
[2025-04-16T07:17:09.982+0000] {processor.py:153} INFO - Started process (PID=757) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:17:09.991+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:17:09.992+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:17:09.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:17:10.099+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:17:10.098+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:17:10.100+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:17:10.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.159 seconds
[2025-04-16T07:17:40.342+0000] {processor.py:153} INFO - Started process (PID=762) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:17:40.351+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:17:40.352+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:17:40.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:17:40.451+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:17:40.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:17:40.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:17:40.481+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.144 seconds
[2025-04-16T07:18:10.522+0000] {processor.py:153} INFO - Started process (PID=767) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:18:10.531+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:18:10.532+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:18:10.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:18:10.642+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:18:10.641+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:18:10.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:18:10.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.165 seconds
[2025-04-16T07:18:40.857+0000] {processor.py:153} INFO - Started process (PID=772) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:18:40.867+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:18:40.869+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:18:40.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:18:40.974+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:18:40.973+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:18:40.975+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:18:41.011+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.159 seconds
[2025-04-16T07:19:11.202+0000] {processor.py:153} INFO - Started process (PID=777) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:19:11.211+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:19:11.213+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:19:11.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:19:11.349+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:19:11.347+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:19:11.349+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:19:11.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.197 seconds
[2025-04-16T07:19:41.598+0000] {processor.py:153} INFO - Started process (PID=782) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:19:41.608+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:19:41.609+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:19:41.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:19:41.712+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:19:41.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:19:41.713+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:19:41.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.148 seconds
[2025-04-16T07:20:11.943+0000] {processor.py:153} INFO - Started process (PID=787) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:20:11.953+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:20:11.955+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:20:11.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:20:12.076+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:20:12.075+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:20:12.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:20:12.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.181 seconds
[2025-04-16T07:20:42.312+0000] {processor.py:153} INFO - Started process (PID=792) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:20:42.314+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:20:42.315+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:20:42.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:20:42.442+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:20:42.440+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:20:42.443+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:20:42.474+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.167 seconds
[2025-04-16T07:21:12.670+0000] {processor.py:153} INFO - Started process (PID=797) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:21:12.679+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:21:12.680+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:21:12.680+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:21:12.810+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:21:12.809+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:21:12.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:21:12.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.187 seconds
[2025-04-16T07:21:43.053+0000] {processor.py:153} INFO - Started process (PID=802) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:21:43.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:21:43.063+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:21:43.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:21:43.168+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:21:43.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:21:43.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:21:43.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.156 seconds
[2025-04-16T07:22:13.402+0000] {processor.py:153} INFO - Started process (PID=807) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:22:13.411+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:22:13.413+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:22:13.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:22:13.533+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:22:13.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:22:13.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:22:13.570+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.174 seconds
[2025-04-16T07:22:43.758+0000] {processor.py:153} INFO - Started process (PID=812) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:22:43.767+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:22:43.769+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:22:43.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:22:43.873+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:22:43.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:22:43.873+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:22:43.908+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.154 seconds
[2025-04-16T07:23:13.950+0000] {processor.py:153} INFO - Started process (PID=817) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T07:23:13.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T07:23:13.952+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:23:13.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T07:23:14.069+0000] {logging_mixin.py:137} INFO - [2025-04-16T07:23:14.067+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T07:23:14.069+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T07:23:14.106+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.160 seconds
[2025-04-16T11:05:37.857+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:05:37.858+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:05:37.859+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:05:37.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:05:38.036+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:05:38.035+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:05:38.036+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:05:38.049+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.193 seconds
[2025-04-16T11:06:08.204+0000] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:06:08.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:06:08.205+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:06:08.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:06:08.253+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:06:08.252+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:06:08.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:06:08.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.068 seconds
[2025-04-16T11:06:38.357+0000] {processor.py:153} INFO - Started process (PID=214) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:06:38.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:06:38.366+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:06:38.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:06:38.419+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:06:38.419+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:06:38.420+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:06:38.433+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.079 seconds
[2025-04-16T11:07:08.517+0000] {processor.py:153} INFO - Started process (PID=219) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:07:08.517+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:07:08.518+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:07:08.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:07:08.566+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:07:08.565+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:07:08.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:07:08.580+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.066 seconds
[2025-04-16T11:07:38.673+0000] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:07:38.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:07:38.682+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:07:38.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:07:38.729+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:07:38.729+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:07:38.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:07:38.743+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.073 seconds
[2025-04-16T11:08:08.812+0000] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:08:08.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:08:08.813+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:08:08.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:08:08.869+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:08:08.868+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:08:08.869+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:08:08.886+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.077 seconds
[2025-04-16T11:08:38.985+0000] {processor.py:153} INFO - Started process (PID=234) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:08:38.994+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:08:38.994+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:08:38.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:08:39.048+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:08:39.047+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:08:39.048+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:08:39.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.081 seconds
[2025-04-16T11:09:09.130+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:09:09.138+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:09:09.139+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:09:09.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:09:09.185+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:09:09.184+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:09:09.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:09:09.199+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.072 seconds
[2025-04-16T11:09:39.319+0000] {processor.py:153} INFO - Started process (PID=244) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:09:39.327+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:09:39.328+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:09:39.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:09:39.377+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:09:39.377+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:09:39.377+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:09:39.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.076 seconds
[2025-04-16T11:10:09.456+0000] {processor.py:153} INFO - Started process (PID=249) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:10:09.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:10:09.465+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:10:09.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:10:09.513+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:10:09.512+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:10:09.513+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:10:09.526+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.073 seconds
[2025-04-16T11:10:39.641+0000] {processor.py:153} INFO - Started process (PID=254) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:10:39.642+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:10:39.642+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:10:39.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:10:39.689+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:10:39.688+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:10:39.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:10:39.704+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.066 seconds
[2025-04-16T11:11:09.777+0000] {processor.py:153} INFO - Started process (PID=259) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:11:09.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:11:09.786+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:11:09.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:11:09.833+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:11:09.832+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:11:09.833+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:11:09.847+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.073 seconds
[2025-04-16T11:11:39.966+0000] {processor.py:153} INFO - Started process (PID=264) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:11:39.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:11:39.975+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:11:39.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:11:40.024+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:11:40.023+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:11:40.024+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:11:40.039+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.076 seconds
[2025-04-16T11:12:10.095+0000] {processor.py:153} INFO - Started process (PID=269) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:12:10.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:12:10.104+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:12:10.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:12:10.151+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:12:10.151+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:12:10.151+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:12:10.165+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.073 seconds
[2025-04-16T11:12:40.266+0000] {processor.py:153} INFO - Started process (PID=274) to work on /opt/airflow/dags/task_dag.py
[2025-04-16T11:12:40.267+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task_dag.py for tasks to queue
[2025-04-16T11:12:40.268+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:12:40.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_dag.py
[2025-04-16T11:12:40.317+0000] {logging_mixin.py:137} INFO - [2025-04-16T11:12:40.316+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_dag.py", line 5, in <module>
    from ..scripts.get_data import fetch_data
ImportError: attempted relative import with no known parent package
[2025-04-16T11:12:40.317+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task_dag.py
[2025-04-16T11:12:40.331+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task_dag.py took 0.067 seconds
