[2025-07-31T12:12:05.015+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-31T12:12:05.031+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: world_population_ETL_dag_43.consume_and_insert_task manual__2025-07-31T12:09:54.468839+00:00 [queued]>
[2025-07-31T12:12:05.039+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: world_population_ETL_dag_43.consume_and_insert_task manual__2025-07-31T12:09:54.468839+00:00 [queued]>
[2025-07-31T12:12:05.039+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-07-31T12:12:05.048+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_and_insert_task> on 2025-07-31 12:09:54.468839+00:00
[2025-07-31T12:12:05.059+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'world_population_ETL_dag_43', 'consume_and_insert_task', 'manual__2025-07-31T12:09:54.468839+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/project_01_dag.py', '--cfg-path', '/tmp/tmpx22tc6hv']
[2025-07-31T12:12:05.061+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T12:12:05.061+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask consume_and_insert_task
[2025-07-31T12:12:05.061+0000] {standard_task_runner.py:72} INFO - Started process 297 to run task
[2025-07-31T12:12:05.094+0000] {task_command.py:467} INFO - Running <TaskInstance: world_population_ETL_dag_43.consume_and_insert_task manual__2025-07-31T12:09:54.468839+00:00 [running]> on host 1e069286f646
[2025-07-31T12:12:05.151+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='givi-abe' AIRFLOW_CTX_DAG_ID='world_population_ETL_dag_43' AIRFLOW_CTX_TASK_ID='consume_and_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T12:09:54.468839+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T12:09:54.468839+00:00'
[2025-07-31T12:12:05.152+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-31T12:12:05.163+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-31T12:12:05.166+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-31T12:12:05.167+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-31T12:12:05.168+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('ETL-PROJECT',)
[2025-07-31T12:12:05.171+0000] {logging_mixin.py:190} INFO - âœ… Connected to PostgreSQL
[2025-07-31T12:12:05.174+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-31T12:12:05.174+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-31T12:12:05.174+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-31T12:12:05.277+0000] {cluster.py:401} INFO - Coordinator for group/my-group is ('coordinator-1', 'kafka', 9092, None)
[2025-07-31T12:12:05.277+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group my-group
[2025-07-31T12:12:05.277+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-31T12:12:05.278+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group my-group
[2025-07-31T12:12:05.278+0000] {base.py:419} INFO - Failed to join group my-group: NodeNotReadyError: coordinator-1
[2025-07-31T12:12:05.279+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-31T12:12:05.279+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-31T12:12:05.380+0000] {base.py:532} INFO - (Re-)joining group my-group
[2025-07-31T12:12:05.382+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-74a7e179-6099-4d4d-9a38-0eae52ca3cfb for group my-group; will retry join-group
[2025-07-31T12:12:05.382+0000] {base.py:419} INFO - Failed to join group my-group: [Error 79] MemberIdRequiredError
[2025-07-31T12:12:05.382+0000] {base.py:532} INFO - (Re-)joining group my-group
[2025-07-31T12:12:06.172+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-31T12:12:06.172+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-31T12:12:06.172+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-31T12:12:06.173+0000] {base.py:569} ERROR - Error sending JoinGroupRequest_v4 to node coordinator-1 [Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>]
[2025-07-31T12:12:06.173+0000] {base.py:810} WARNING - Marking the coordinator dead (node coordinator-1) for group my-group: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>.
[2025-07-31T12:12:06.173+0000] {base.py:419} INFO - Failed to join group my-group: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-31T12:12:06.173+0000] {logging_mixin.py:190} INFO - ðŸ”Œ PostgreSQL connection closed.
[2025-07-31T12:12:06.173+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-31T12:12:06.182+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-31T12:12:06.183+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=world_population_ETL_dag_43, task_id=consume_and_insert_task, run_id=manual__2025-07-31T12:09:54.468839+00:00, execution_date=20250731T120954, start_date=20250731T121205, end_date=20250731T121206
[2025-07-31T12:12:06.237+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-31T12:12:06.258+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-31T12:12:06.259+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
