[2025-04-04T05:20:23.870+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.fetch_data manual__2025-04-04T05:20:22.924799+00:00 [queued]>
[2025-04-04T05:20:23.877+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.fetch_data manual__2025-04-04T05:20:22.924799+00:00 [queued]>
[2025-04-04T05:20:23.877+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T05:20:23.877+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-04T05:20:23.877+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T05:20:23.887+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): fetch_data> on 2025-04-04 05:20:22.924799+00:00
[2025-04-04T05:20:23.893+0000] {standard_task_runner.py:55} INFO - Started process 238 to run task
[2025-04-04T05:20:23.895+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'fetch_data', 'manual__2025-04-04T05:20:22.924799+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmphq1drp4i']
[2025-04-04T05:20:23.897+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask fetch_data
[2025-04-04T05:20:23.939+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.fetch_data manual__2025-04-04T05:20:22.924799+00:00 [running]> on host 02c55f5ad405
[2025-04-04T05:20:23.989+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HemaDag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2025-04-04T05:20:22.924799+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-04T05:20:22.924799+00:00
[2025-04-04T05:20:23.990+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-04-04T05:20:23.990+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/scripts/Extract.py']
[2025-04-04T05:20:24.003+0000] {subprocess.py:86} INFO - Output:
[2025-04-04T05:20:24.068+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/dags/scripts/Extract.py': [Errno 2] No such file or directory
[2025-04-04T05:20:24.070+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-04T05:20:24.079+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-04T05:20:24.082+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=HemaDag, task_id=fetch_data, execution_date=20250404T052022, start_date=20250404T052023, end_date=20250404T052024
[2025-04-04T05:20:24.092+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task fetch_data (Bash command failed. The command returned a non-zero exit code 2.; 238)
[2025-04-04T05:20:24.107+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-04T05:20:24.121+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
