[2025-04-15T04:45:09.057+0000] {processor.py:153} INFO - Started process (PID=204) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:45:09.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:45:09.059+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:45:09.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:45:09.461+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:45:09.461+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:45:09.462+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:45:09.477+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.422 seconds
[2025-04-15T04:45:39.544+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:45:39.553+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:45:39.554+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:45:39.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:45:39.886+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:45:39.883+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:45:39.886+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:45:39.919+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.380 seconds
[2025-04-15T04:46:10.135+0000] {processor.py:153} INFO - Started process (PID=232) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:46:10.137+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:46:10.138+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:46:10.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:46:10.506+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:46:10.503+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:46:10.507+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:46:10.549+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.420 seconds
[2025-04-15T04:46:41.328+0000] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:46:41.337+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:46:41.338+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:46:41.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:46:41.655+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:46:41.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:46:41.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:46:41.691+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.368 seconds
[2025-04-15T04:47:11.761+0000] {processor.py:153} INFO - Started process (PID=254) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:47:11.762+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:47:11.763+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:47:11.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:47:12.005+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:47:12.003+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:47:12.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:47:12.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.268 seconds
[2025-04-15T04:47:42.099+0000] {processor.py:153} INFO - Started process (PID=265) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:47:42.101+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:47:42.102+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:47:42.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:47:42.425+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:47:42.422+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:47:42.426+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:47:42.455+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.361 seconds
[2025-04-15T04:48:13.305+0000] {processor.py:153} INFO - Started process (PID=276) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:48:13.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:48:13.308+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:48:13.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:48:13.665+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:48:13.661+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:48:13.665+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:48:13.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.393 seconds
[2025-04-15T04:48:43.850+0000] {processor.py:153} INFO - Started process (PID=287) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:48:43.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:48:43.860+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:48:43.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:48:44.217+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:48:44.214+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:48:44.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:48:44.254+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.410 seconds
[2025-04-15T04:49:15.052+0000] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:49:15.061+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:49:15.062+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:49:15.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:49:15.390+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:49:15.386+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:49:15.390+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:49:15.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.378 seconds
[2025-04-15T04:49:45.578+0000] {processor.py:153} INFO - Started process (PID=309) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:49:45.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:49:45.589+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:49:45.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:49:45.935+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:49:45.931+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:49:45.935+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:49:45.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.386 seconds
[2025-04-15T04:50:16.778+0000] {processor.py:153} INFO - Started process (PID=320) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:50:16.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:50:16.789+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:50:16.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:50:17.121+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:50:17.118+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:50:17.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:50:17.156+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.382 seconds
[2025-04-15T04:50:47.298+0000] {processor.py:153} INFO - Started process (PID=331) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:50:47.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:50:47.301+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:50:47.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:50:47.638+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:50:47.634+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:50:47.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:50:47.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.378 seconds
[2025-04-15T04:51:18.498+0000] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:51:18.508+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:51:18.509+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:51:18.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:51:18.876+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:51:18.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:51:18.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:51:18.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.418 seconds
[2025-04-15T04:51:49.034+0000] {processor.py:153} INFO - Started process (PID=353) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:51:49.043+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:51:49.045+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:51:49.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:51:49.372+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:51:49.369+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:51:49.373+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:51:49.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.379 seconds
[2025-04-15T04:52:20.223+0000] {processor.py:153} INFO - Started process (PID=364) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:52:20.230+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:52:20.232+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:52:20.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:52:20.570+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:52:20.566+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:52:20.570+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:52:20.605+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.388 seconds
[2025-04-15T04:52:50.739+0000] {processor.py:153} INFO - Started process (PID=375) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:52:50.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:52:50.749+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:52:50.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:52:51.095+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:52:51.091+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:52:51.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:52:51.132+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.398 seconds
[2025-04-15T04:53:21.932+0000] {processor.py:153} INFO - Started process (PID=386) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:53:21.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:53:21.942+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:53:21.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:53:22.302+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:53:22.299+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:53:22.303+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:53:22.344+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.417 seconds
[2025-04-15T04:53:52.434+0000] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:53:52.442+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:53:52.443+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:53:52.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:53:52.773+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:53:52.770+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:53:52.773+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:53:52.801+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.372 seconds
[2025-04-15T04:54:23.615+0000] {processor.py:153} INFO - Started process (PID=408) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:54:23.624+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:54:23.625+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:54:23.625+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:54:23.971+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:54:23.968+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:54:23.972+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:54:24.006+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.395 seconds
[2025-04-15T04:54:54.082+0000] {processor.py:153} INFO - Started process (PID=419) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:54:54.090+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:54:54.091+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:54:54.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:54:54.455+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:54:54.451+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:54:54.455+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:54:54.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.413 seconds
[2025-04-15T04:55:25.278+0000] {processor.py:153} INFO - Started process (PID=430) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:55:25.287+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:55:25.289+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:55:25.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:55:25.636+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:55:25.633+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:55:25.636+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:55:25.671+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.398 seconds
[2025-04-15T04:55:55.788+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:55:55.789+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:55:55.790+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:55:55.790+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:55:56.135+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:55:56.132+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:55:56.135+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:55:56.171+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.388 seconds
[2025-04-15T04:56:26.969+0000] {processor.py:153} INFO - Started process (PID=452) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:56:26.978+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:56:26.979+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:56:26.979+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:56:27.323+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:56:27.320+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:56:27.324+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:56:27.357+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.393 seconds
[2025-04-15T04:56:57.477+0000] {processor.py:153} INFO - Started process (PID=463) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:56:57.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:56:57.488+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:56:57.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:56:57.821+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:56:57.817+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:56:57.821+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:56:57.855+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.383 seconds
[2025-04-15T04:57:28.654+0000] {processor.py:153} INFO - Started process (PID=474) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:57:28.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:57:28.665+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:57:28.665+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:57:28.999+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:57:28.996+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:57:29.000+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:57:29.024+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.376 seconds
[2025-04-15T04:57:59.165+0000] {processor.py:153} INFO - Started process (PID=485) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:57:59.174+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:57:59.176+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:57:59.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:57:59.509+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:57:59.506+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:57:59.509+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:57:59.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.382 seconds
[2025-04-15T04:58:30.354+0000] {processor.py:153} INFO - Started process (PID=496) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:58:30.355+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:58:30.356+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:58:30.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:58:30.754+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:58:30.750+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:58:30.754+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:58:30.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.436 seconds
[2025-04-15T04:59:00.872+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:59:00.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:59:00.882+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:59:00.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:59:01.241+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:59:01.238+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:59:01.241+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:59:01.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.410 seconds
[2025-04-15T04:59:32.041+0000] {processor.py:153} INFO - Started process (PID=518) to work on /opt/airflow/dags/Transform.py
[2025-04-15T04:59:32.050+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T04:59:32.051+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:59:32.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T04:59:32.391+0000] {logging_mixin.py:137} INFO - [2025-04-15T04:59:32.388+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T04:59:32.391+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T04:59:32.425+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.389 seconds
[2025-04-15T05:00:02.551+0000] {processor.py:153} INFO - Started process (PID=529) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:00:02.560+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:00:02.561+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:00:02.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:00:02.894+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:00:02.891+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:00:02.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:00:02.919+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.373 seconds
[2025-04-15T05:00:33.735+0000] {processor.py:153} INFO - Started process (PID=540) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:00:33.744+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:00:33.745+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:00:33.745+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:00:34.079+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:00:34.076+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:00:34.079+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:00:34.105+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.375 seconds
[2025-04-15T05:01:04.249+0000] {processor.py:153} INFO - Started process (PID=551) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:01:04.250+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:01:04.251+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:01:04.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:01:04.583+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:01:04.580+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:01:04.584+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:01:04.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.372 seconds
[2025-04-15T05:01:35.426+0000] {processor.py:153} INFO - Started process (PID=562) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:01:35.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:01:35.437+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:01:35.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:01:35.786+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:01:35.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:01:35.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:01:35.819+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.399 seconds
[2025-04-15T05:02:05.957+0000] {processor.py:153} INFO - Started process (PID=573) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:02:05.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:02:05.967+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:02:05.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:02:06.294+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:02:06.291+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:02:06.294+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:02:06.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.368 seconds
[2025-04-15T05:02:37.139+0000] {processor.py:153} INFO - Started process (PID=584) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:02:37.148+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:02:37.149+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:02:37.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:02:37.487+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:02:37.484+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:02:37.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:02:37.521+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.387 seconds
[2025-04-15T05:03:07.644+0000] {processor.py:153} INFO - Started process (PID=595) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:03:07.652+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:03:07.654+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:03:07.653+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:03:07.990+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:03:07.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:03:07.991+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:03:08.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.385 seconds
[2025-04-15T05:03:38.825+0000] {processor.py:153} INFO - Started process (PID=606) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:03:38.834+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:03:38.835+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:03:38.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:03:39.170+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:03:39.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:03:39.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:03:39.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.383 seconds
[2025-04-15T05:04:09.317+0000] {processor.py:153} INFO - Started process (PID=617) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:04:09.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:04:09.327+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:04:09.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:04:09.660+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:04:09.657+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:04:09.660+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:04:09.694+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.382 seconds
[2025-04-15T05:04:40.494+0000] {processor.py:153} INFO - Started process (PID=628) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:04:40.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:04:40.504+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:04:40.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:04:40.837+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:04:40.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:04:40.838+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:04:40.871+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.381 seconds
[2025-04-15T05:05:10.998+0000] {processor.py:153} INFO - Started process (PID=639) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:05:11.007+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:05:11.008+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:05:11.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:05:11.344+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:05:11.342+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:05:11.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:05:11.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.386 seconds
[2025-04-15T05:05:42.178+0000] {processor.py:153} INFO - Started process (PID=650) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:05:42.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:05:42.189+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:05:42.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:05:42.530+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:05:42.527+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:05:42.530+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:05:42.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.390 seconds
[2025-04-15T05:06:12.683+0000] {processor.py:153} INFO - Started process (PID=661) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:06:12.692+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:06:12.693+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:06:12.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:06:13.028+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:06:13.025+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:06:13.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:06:13.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.384 seconds
[2025-04-15T05:06:43.866+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:06:43.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:06:43.876+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:06:43.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:06:44.216+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:06:44.213+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:06:44.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:06:44.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.391 seconds
[2025-04-15T05:07:14.352+0000] {processor.py:153} INFO - Started process (PID=683) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:07:14.361+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:07:14.362+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:07:14.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:07:14.708+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:07:14.705+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:07:14.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:07:14.743+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.396 seconds
[2025-04-15T05:07:45.539+0000] {processor.py:153} INFO - Started process (PID=694) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:07:45.540+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:07:45.541+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:07:45.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:07:45.883+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:07:45.880+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:07:45.883+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:07:45.915+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.382 seconds
[2025-04-15T05:08:16.026+0000] {processor.py:153} INFO - Started process (PID=705) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:08:16.035+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:08:16.037+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:08:16.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:08:16.369+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:08:16.366+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:08:16.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:08:16.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.384 seconds
[2025-04-15T05:08:47.209+0000] {processor.py:153} INFO - Started process (PID=716) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:08:47.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:08:47.219+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:08:47.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:08:47.551+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:08:47.548+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:08:47.551+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:08:47.588+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.384 seconds
[2025-04-15T05:09:17.705+0000] {processor.py:153} INFO - Started process (PID=727) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:09:17.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:09:17.707+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:09:17.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:09:18.086+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:09:18.083+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:09:18.087+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:09:18.123+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.423 seconds
[2025-04-15T05:09:48.880+0000] {processor.py:153} INFO - Started process (PID=738) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:09:48.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:09:48.891+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:09:48.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:09:49.227+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:09:49.224+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:09:49.228+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:09:49.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.376 seconds
[2025-04-15T05:10:19.424+0000] {processor.py:153} INFO - Started process (PID=749) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:10:19.433+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:10:19.434+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:10:19.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:10:19.771+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:10:19.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:10:19.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:10:19.806+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.387 seconds
[2025-04-15T05:10:50.599+0000] {processor.py:153} INFO - Started process (PID=760) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:10:50.608+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:10:50.610+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:10:50.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:10:50.941+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:10:50.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:10:50.942+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:10:50.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.371 seconds
[2025-04-15T05:11:21.098+0000] {processor.py:153} INFO - Started process (PID=771) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:11:21.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:11:21.108+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:11:21.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:11:21.445+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:11:21.441+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:11:21.445+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:11:21.480+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.386 seconds
[2025-04-15T05:11:52.277+0000] {processor.py:153} INFO - Started process (PID=782) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:11:52.286+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:11:52.287+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:11:52.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:11:52.625+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:11:52.622+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:11:52.626+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:11:52.662+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.390 seconds
[2025-04-15T05:12:22.782+0000] {processor.py:153} INFO - Started process (PID=793) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:12:22.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:12:22.793+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:12:22.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:12:23.133+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:12:23.129+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:12:23.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:12:23.163+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.385 seconds
[2025-04-15T05:12:53.969+0000] {processor.py:153} INFO - Started process (PID=804) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:12:53.978+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:12:53.980+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:12:53.979+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:12:54.314+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:12:54.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:12:54.315+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:12:54.349+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.384 seconds
[2025-04-15T05:13:24.439+0000] {processor.py:153} INFO - Started process (PID=815) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:13:24.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:13:24.449+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:13:24.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:13:24.790+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:13:24.787+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:13:24.790+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:13:24.817+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.383 seconds
[2025-04-15T05:13:55.628+0000] {processor.py:153} INFO - Started process (PID=826) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:13:55.637+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:13:55.638+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:13:55.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:13:55.976+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:13:55.973+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:13:55.977+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:13:56.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.388 seconds
[2025-04-15T05:14:26.109+0000] {processor.py:153} INFO - Started process (PID=837) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:14:26.117+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:14:26.119+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:14:26.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:14:26.451+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:14:26.449+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:14:26.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:14:26.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.381 seconds
[2025-04-15T05:14:57.284+0000] {processor.py:153} INFO - Started process (PID=848) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:14:57.293+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:14:57.294+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:14:57.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:14:57.628+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:14:57.626+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:14:57.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:14:57.664+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.384 seconds
[2025-04-15T05:15:27.784+0000] {processor.py:153} INFO - Started process (PID=859) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:15:27.793+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:15:27.794+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:15:27.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:15:28.128+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:15:28.125+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:15:28.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:15:28.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.389 seconds
[2025-04-15T05:15:58.971+0000] {processor.py:153} INFO - Started process (PID=870) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:15:58.980+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:15:58.981+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:15:58.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:15:59.315+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:15:59.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:15:59.316+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:15:59.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.382 seconds
[2025-04-15T05:16:29.420+0000] {processor.py:153} INFO - Started process (PID=881) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:16:29.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:16:29.431+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:16:29.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:16:29.760+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:16:29.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:16:29.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:16:29.797+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.381 seconds
[2025-04-15T05:17:00.596+0000] {processor.py:153} INFO - Started process (PID=892) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:17:00.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:17:00.605+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:17:00.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:17:00.944+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:17:00.941+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:17:00.945+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:17:00.969+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.380 seconds
[2025-04-15T05:17:31.094+0000] {processor.py:153} INFO - Started process (PID=903) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:17:31.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:17:31.104+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:17:31.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:17:31.439+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:17:31.436+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:17:31.439+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:17:31.471+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.383 seconds
[2025-04-15T05:18:01.622+0000] {processor.py:153} INFO - Started process (PID=919) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:18:01.624+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:18:01.625+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:18:01.624+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:18:01.951+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:18:01.947+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:18:01.951+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:18:01.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.369 seconds
[2025-04-15T05:18:32.800+0000] {processor.py:153} INFO - Started process (PID=930) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:18:32.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:18:32.810+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:18:32.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:18:33.151+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:18:33.148+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:18:33.151+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:18:33.184+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.389 seconds
[2025-04-15T05:19:03.340+0000] {processor.py:153} INFO - Started process (PID=941) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:19:03.349+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:19:03.350+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:19:03.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:19:03.700+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:19:03.697+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:19:03.700+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:19:03.734+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.400 seconds
[2025-04-15T05:19:34.513+0000] {processor.py:153} INFO - Started process (PID=952) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:19:34.522+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:19:34.524+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:19:34.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:19:34.863+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:19:34.860+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:19:34.863+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:19:34.894+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.385 seconds
[2025-04-15T05:20:05.020+0000] {processor.py:153} INFO - Started process (PID=963) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:20:05.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:20:05.031+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:20:05.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:20:05.363+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:20:05.360+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:20:05.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:20:05.399+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.383 seconds
[2025-04-15T05:20:36.213+0000] {processor.py:153} INFO - Started process (PID=974) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:20:36.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:20:36.222+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:20:36.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:20:36.560+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:20:36.557+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:20:36.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:20:36.593+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.385 seconds
[2025-04-15T05:21:06.738+0000] {processor.py:153} INFO - Started process (PID=985) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:21:06.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:21:06.748+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:21:06.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:21:07.084+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:21:07.081+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:21:07.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:21:07.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.390 seconds
[2025-04-15T05:21:37.922+0000] {processor.py:153} INFO - Started process (PID=996) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:21:37.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:21:37.924+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:21:37.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:21:38.264+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:21:38.261+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:21:38.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:21:38.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.373 seconds
[2025-04-15T05:22:08.479+0000] {processor.py:153} INFO - Started process (PID=1007) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:22:08.488+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:22:08.489+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:22:08.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:22:08.859+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:22:08.855+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:22:08.860+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:22:08.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.423 seconds
[2025-04-15T05:22:39.655+0000] {processor.py:153} INFO - Started process (PID=1018) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:22:39.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:22:39.665+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:22:39.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:22:39.986+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:22:39.984+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:22:39.987+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:22:40.008+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.358 seconds
[2025-04-15T05:23:10.164+0000] {processor.py:153} INFO - Started process (PID=1029) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:23:10.173+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:23:10.174+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:23:10.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:23:10.528+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:23:10.525+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:23:10.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:23:10.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.406 seconds
[2025-04-15T05:23:41.356+0000] {processor.py:153} INFO - Started process (PID=1040) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:23:41.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:23:41.367+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:23:41.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:23:41.702+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:23:41.698+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:23:41.702+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:23:41.739+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.387 seconds
[2025-04-15T05:24:11.938+0000] {processor.py:153} INFO - Started process (PID=1051) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:24:11.947+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:24:11.948+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:24:11.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:24:12.341+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:24:12.336+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:24:12.341+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:24:12.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.447 seconds
[2025-04-15T05:24:43.139+0000] {processor.py:153} INFO - Started process (PID=1062) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:24:43.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:24:43.142+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:24:43.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:24:43.542+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:24:43.539+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:24:43.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:24:43.577+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.444 seconds
[2025-04-15T05:25:13.726+0000] {processor.py:153} INFO - Started process (PID=1073) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:25:13.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:25:13.736+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:25:13.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:25:14.056+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:25:14.052+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:25:14.056+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:25:14.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.373 seconds
[2025-04-15T05:25:44.934+0000] {processor.py:153} INFO - Started process (PID=1084) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:25:44.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:25:44.936+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:25:44.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:25:45.306+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:25:45.303+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:25:45.307+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:25:45.341+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.413 seconds
[2025-04-15T05:26:15.478+0000] {processor.py:153} INFO - Started process (PID=1095) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:26:15.487+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:26:15.488+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:26:15.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:26:15.842+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:26:15.839+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:26:15.843+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:26:15.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.406 seconds
[2025-04-15T05:26:46.669+0000] {processor.py:153} INFO - Started process (PID=1106) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:26:46.678+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:26:46.679+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:26:46.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:26:47.037+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:26:47.034+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:26:47.038+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:26:47.071+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.406 seconds
[2025-04-15T05:27:17.203+0000] {processor.py:153} INFO - Started process (PID=1117) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:27:17.209+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:27:17.210+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:27:17.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:27:17.539+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:27:17.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:27:17.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:27:17.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.376 seconds
[2025-04-15T05:27:48.384+0000] {processor.py:153} INFO - Started process (PID=1128) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:27:48.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:27:48.393+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:27:48.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:27:48.778+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:27:48.775+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:27:48.778+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:27:48.817+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.438 seconds
[2025-04-15T05:28:18.932+0000] {processor.py:153} INFO - Started process (PID=1139) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:28:18.933+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:28:18.934+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:28:18.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:28:19.323+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:28:19.319+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:28:19.323+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:28:19.358+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.431 seconds
[2025-04-15T05:28:50.135+0000] {processor.py:153} INFO - Started process (PID=1150) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:28:50.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:28:50.146+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:28:50.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:28:50.527+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:28:50.525+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:28:50.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:28:50.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.435 seconds
[2025-04-15T05:29:20.682+0000] {processor.py:153} INFO - Started process (PID=1166) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:29:20.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:29:20.685+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:29:20.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:29:21.043+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:29:21.039+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:29:21.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:29:21.086+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.409 seconds
[2025-04-15T05:29:51.880+0000] {processor.py:153} INFO - Started process (PID=1177) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:29:51.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:29:51.882+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:29:51.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:29:52.229+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:29:52.226+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:29:52.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:29:52.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.391 seconds
[2025-04-15T05:30:22.391+0000] {processor.py:153} INFO - Started process (PID=1188) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:30:22.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:30:22.401+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:30:22.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:30:22.799+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:30:22.795+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:30:22.800+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:30:22.838+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.453 seconds
[2025-04-15T05:30:53.585+0000] {processor.py:153} INFO - Started process (PID=1199) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:30:53.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:30:53.595+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:30:53.595+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:30:53.964+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:30:53.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:30:53.964+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:30:53.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.408 seconds
[2025-04-15T05:31:24.119+0000] {processor.py:153} INFO - Started process (PID=1210) to work on /opt/airflow/dags/Transform.py
[2025-04-15T05:31:24.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/Transform.py for tasks to queue
[2025-04-15T05:31:24.129+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:31:24.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/Transform.py
[2025-04-15T05:31:24.486+0000] {logging_mixin.py:137} INFO - [2025-04-15T05:31:24.484+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/Transform.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Transform.py", line 2, in <module>
    from dags.Extract import get_data
ModuleNotFoundError: No module named 'dags'
[2025-04-15T05:31:24.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/Transform.py
[2025-04-15T05:31:24.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/Transform.py took 0.404 seconds
