[2025-04-14T15:36:58.956+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.send_to_kafka manual__2025-04-14T15:36:47.621693+00:00 [queued]>
[2025-04-14T15:36:58.968+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.send_to_kafka manual__2025-04-14T15:36:47.621693+00:00 [queued]>
[2025-04-14T15:36:58.968+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:36:58.968+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-14T15:36:58.968+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:36:58.985+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): send_to_kafka> on 2025-04-14 15:36:47.621693+00:00
[2025-04-14T15:36:58.998+0000] {standard_task_runner.py:55} INFO - Started process 1196 to run task
[2025-04-14T15:36:59.002+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'send_to_kafka', 'manual__2025-04-14T15:36:47.621693+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmp27e_xhuk']
[2025-04-14T15:36:59.005+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask send_to_kafka
[2025-04-14T15:36:59.094+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.send_to_kafka manual__2025-04-14T15:36:47.621693+00:00 [running]> on host 0c4d66587ca1
[2025-04-14T15:36:59.194+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HemaDag
AIRFLOW_CTX_TASK_ID=send_to_kafka
AIRFLOW_CTX_EXECUTION_DATE=2025-04-14T15:36:47.621693+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-14T15:36:47.621693+00:00
[2025-04-14T15:36:59.196+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-04-14T15:36:59.196+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/kafka_producer.py']
[2025-04-14T15:36:59.219+0000] {subprocess.py:86} INFO - Output:
[2025-04-14T15:36:59.347+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-14T15:36:59.348+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/kafka_producer.py", line 1, in <module>
[2025-04-14T15:36:59.348+0000] {subprocess.py:93} INFO -     from scripts.kafka_producer import KafkaProducer, KafkaConsumer
[2025-04-14T15:36:59.348+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'scripts'
[2025-04-14T15:36:59.351+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-14T15:36:59.368+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-14T15:36:59.373+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=HemaDag, task_id=send_to_kafka, execution_date=20250414T153647, start_date=20250414T153658, end_date=20250414T153659
[2025-04-14T15:36:59.398+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task send_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 1196)
[2025-04-14T15:36:59.414+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-14T15:36:59.451+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
