[2025-04-14T15:08:33.784+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.create_table manual__2025-04-14T15:08:32.384542+00:00 [queued]>
[2025-04-14T15:08:33.800+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: HemaDag.create_table manual__2025-04-14T15:08:32.384542+00:00 [queued]>
[2025-04-14T15:08:33.800+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:08:33.800+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-04-14T15:08:33.800+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-14T15:08:33.822+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): create_table> on 2025-04-14 15:08:32.384542+00:00
[2025-04-14T15:08:33.832+0000] {standard_task_runner.py:55} INFO - Started process 451 to run task
[2025-04-14T15:08:33.837+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'HemaDag', 'create_table', 'manual__2025-04-14T15:08:32.384542+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/day.py', '--cfg-path', '/tmp/tmp9pbgn1f8']
[2025-04-14T15:08:33.840+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask create_table
[2025-04-14T15:08:33.936+0000] {task_command.py:388} INFO - Running <TaskInstance: HemaDag.create_table manual__2025-04-14T15:08:32.384542+00:00 [running]> on host 0c4d66587ca1
[2025-04-14T15:08:34.048+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HemaDag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-04-14T15:08:32.384542+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-14T15:08:32.384542+00:00
[2025-04-14T15:08:34.050+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-04-14T15:08:34.050+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/create_table.py']
[2025-04-14T15:08:34.072+0000] {subprocess.py:86} INFO - Output:
[2025-04-14T15:08:34.784+0000] {subprocess.py:93} INFO - ✅ Connected to PostgreSQL
[2025-04-14T15:08:34.784+0000] {subprocess.py:93} INFO - ❌ Error creating table: syntax error at or near "exist"
[2025-04-14T15:08:34.784+0000] {subprocess.py:93} INFO - LINE 2:             create table if not exist world_population(
[2025-04-14T15:08:34.784+0000] {subprocess.py:93} INFO -                                         ^
[2025-04-14T15:08:34.785+0000] {subprocess.py:93} INFO - 
[2025-04-14T15:08:34.785+0000] {subprocess.py:93} INFO - ✅ PostgreSQL connection closed
[2025-04-14T15:08:34.825+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-14T15:08:34.883+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=HemaDag, task_id=create_table, execution_date=20250414T150832, start_date=20250414T150833, end_date=20250414T150834
[2025-04-14T15:08:34.931+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-14T15:08:34.957+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
